#!/usr/bin/env python3
"""
Generate protobuf bindings from proto/ws2812.proto.

  C / nanopb  — generated by CMake at build time (no need to run this for C)
  Python      — ws2812_pb2.py written to proto/

Run from the examples/pico directory with the project venv active:
  python gen_proto.py
"""

import sys
from pathlib import Path

HERE       = Path(__file__).parent.resolve()
PROTO_DIR  = HERE / "proto"
PROTO_FILE = PROTO_DIR / "ws2812.proto"
PY_OUT     = PROTO_DIR

def main() -> None:
    try:
        from grpc_tools import protoc
    except ImportError:
        sys.exit(
            "grpcio-tools not found — activate the venv and run:\n"
            "  pip install -r requirements.txt"
        )

    ret = protoc.main([
        "grpc_tools.protoc",
        f"-I{PROTO_DIR}",
        f"--python_out={PY_OUT}",
        str(PROTO_FILE),
    ])
    if ret != 0:
        sys.exit(f"protoc failed (exit {ret})")

    print(f"Generated {PY_OUT / 'ws2812_pb2.py'}")

if __name__ == "__main__":
    main()
